apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-web
  labels:
    app: py-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-web
  template:
    metadata:
      labels:
        app: py-web
    spec:
      containers:
      - name: py-web
        image: py-web:v1.0.0
        ports:
        - containerPort: 80
